version: '3'
services:
  db:
      image: microsoft/mssql-server-linux:latest
      ports:
        - 1433:1433
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Test@1234
        - MSSQL_PID=Express
        - MSSQL_LCID=1041
        - MSSQL_COLLATION=Japanese_CI_AS
      volumes:
        - ./init/sql:/init-data
        - ./init/shell/start-up.sh:/start-up.sh
      command: "sh -c '/start-up.sh & /opt/mssql/bin/sqlservr;'"